#!/usr/bin/python3.1

import os
import subprocess

print("Synchronization script which copies all uncommitted changes to the web server")
print("=============================================================================\n")

# Only needed when there are remote changes
#output = subprocess.getoutput("svn up")
#print("SVN " + output + "\n")

output = subprocess.getoutput("svn stat")
lines = output.split("\n")
for line in lines:
	line = line.split("  ")
	info = line[0]
	line = line[len(line)-1]
	line = line.lstrip()
	if line == "deploy":
		continue
	if info == "D":
		print("DEL " + line)
		os.system("ssh eos 'rm -rf " + line + " eos:/www/beachaholics/" + line + "'")		
	else:
		print("MOV " + line)
		os.system("scp -q " + line + " eos:/www/beachaholics/" + line)	
	


